memcached:
  cache:
    servers: localhost:11211
    expiration: 5s
    authentication:
      username: my_user
      password: my_password
      mechanism: plain
    operation-timeout: 3000
    servers-refresh-interval: 4000
    protocol: binary
